### ISSUE TITLE
请问nodejs是多少版本？

### ISSUE THREAD

**Issue by Im-Sue** [novicezk/wechat-midjourney#19]
请问nodejs是多少版本？

**Comment by yexiaobai** [comment]
我的npm install没有报错。
npm run serve报错。
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node@14/14.21.3_1/bin/node',
1 verbose cli   '/usr/local/opt/node@14/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle wechat-midjourney@2.0.2~preserve: wechat-midjourney@2.0.2
6 info lifecycle wechat-midjourney@2.0.2~serve: wechat-midjourney@2.0.2
7 verbose lifecycle wechat-midjourney@2.0.2~serve: unsafe-perm in lifecycle true
8 verbose lifecycle wechat-midjourney@2.0.2~serve: PATH: /usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhengxijun/Documents/workspace/web/wechat-midjourney/node_modules/.bin:/Users/zhengxijun/go/bin:/Applications/PyCharm.app/Contents/MacOS/pycharm:/usr/local/opt/node@14/bin:/usr/local/opt/node@14/bin:/usr/local/var/pyenv/bin:/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zhengxijun/go/bin:/Applications/PyCharm.app/Contents/MacOS/pycharm:/usr/local/opt/node@14/bin:/usr/local/var/pyenv/bin:/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin:.:.
9 verbose lifecycle wechat-midjourney@2.0.2~serve: CWD: /Users/zhengxijun/Documents/workspace/web/wechat-midjourney
10 silly lifecycle wechat-midjourney@2.0.2~serve: Args: [ '-c', 'node --loader ts-node/esm src/main.ts' ]
11 silly lifecycle wechat-midjourney@2.0.2~serve: Returned: code: 1  signal: null
12 info lifecycle wechat-midjourney@2.0.2~serve: Failed to exec serve script
13 verbose stack Error: wechat-midjourney@2.0.2 serve: `node --loader ts-node/esm src/main.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid wechat-midjourney@2.0.2
15 verbose cwd /Users/zhengxijun/Documents/workspace/web/wechat-midjourney
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/Cellar/node@14/14.21.3_1/bin/node" "/usr/local/opt/node@14/bin/npm" "run" "serve"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error wechat-midjourney@2.0.2 serve: `node --loader ts-node/esm src/main.ts`
22 error Exit status 1
23 error Failed at the wechat-midjourney@2.0.2 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
这是报错信息，哪位老哥有没有遇到相同的问题？是不是node和npm的版本问题?

**Comment by yexiaobai** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node@14/14.21.3_1/bin/node',
1 verbose cli   '/usr/local/opt/node@14/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle wechat-midjourney@2.0.2~preserve: wechat-midjourney@2.0.2
6 info lifecycle wechat-midjourney@2.0.2~serve: wechat-midjourney@2.0.2
7 verbose lifecycle wechat-midjourney@2.0.2~serve: unsafe-perm in lifecycle true
8 verbose lifecycle wechat-midjourney@2.0.2~serve: PATH: /usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zhengxijun/Documents/workspace/web/wechat-midjourney/node_modules/.bin:/Users/zhengxijun/go/bin:/Applications/PyCharm.app/Contents/MacOS/pycharm:/usr/local/opt/node@14/bin:/usr/local/opt/node@14/bin:/usr/local/var/pyenv/bin:/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zhengxijun/go/bin:/Applications/PyCharm.app/Contents/MacOS/pycharm:/usr/local/opt/node@14/bin:/usr/local/var/pyenv/bin:/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin:.:.
9 verbose lifecycle wechat-midjourney@2.0.2~serve: CWD: /Users/zhengxijun/Documents/workspace/web/wechat-midjourney
10 silly lifecycle wechat-midjourney@2.0.2~serve: Args: [ '-c', 'node --loader ts-node/esm src/main.ts' ]
11 silly lifecycle wechat-midjourney@2.0.2~serve: Returned: code: 1  signal: null
12 info lifecycle wechat-midjourney@2.0.2~serve: Failed to exec serve script
13 verbose stack Error: wechat-midjourney@2.0.2 serve: `node --loader ts-node/esm src/main.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@14/14.21.3_1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid wechat-midjourney@2.0.2
15 verbose cwd /Users/zhengxijun/Documents/workspace/web/wechat-midjourney
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/Cellar/node@14/14.21.3_1/bin/node" "/usr/local/opt/node@14/bin/npm" "run" "serve"
18 verbose node v14.21.3
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error wechat-midjourney@2.0.2 serve: `node --loader ts-node/esm src/main.ts`
22 error Exit status 1
23 error Failed at the wechat-midjourney@2.0.2 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by yexiaobai** [comment]
2 info using npm@6.14.18
3 info using node@v14.21.3

我的没跑起来，有没有遇到相同问题的老哥
